# Numpy Basic Concepts ##

## 1 What is Numpy ?

NumPy is the fundamental package for scientific computing with Python. It is:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) and [Benefit of Open Source Python versus commercial packages](https://scipy.github.io/old-wiki/pages/NumPyProConPage.html). For an idea of the Open Source Approach to science, we suggest the [Science Code Manifesto](http://sciencecodemanifesto.org/)

### 1.1 Documentation and reference:

* [Numpy Reference guide](http://docs.scipy.org/doc/numpy/reference/)
* [SciPy Reference](http://docs.scipy.org/doc/scipy/reference/)
* [Scipy Topical Software](http://www.scipy.org/Topical_Software)
* [Numpy Functions by Category](http://www.scipy.org/Numpy_Functions_by_Category)
* [Numpy Example List With Doc](http://www.scipy.org/Numpy_Example_List_With_Doc)  

Lets start by checking the Numpy version used in this Notebook:

In [1]:
import numpy as np
print ('numpy version: ', np.__version__)

numpy version:  1.17.3


## 2 Array Creation

NumPy's main object is the homogeneous ***multidimensional array***. It is a table of elements (usually numbers), all of the **same type**. In Numpy dimensions are called ***axes***. The number of axes is called ***rank***. The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

In [ ]:
# 1-d array:
a = np.array([0,1,2,3])
np.shape(a)
a

When we create our array, it is possible to set properly the *ndmin* parameter in order to change the dimension of the given array (and so the shape).
Remember that the method *np.shape()* outputs a tuple, even when *dim*=1.

In [135]:
a = np.array([0,1,2,3], ndmin=2)
a.shape # the same as np.shape(a)
        # one row, four columns

(1, 4)

In [137]:
# 2-d array
b = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
b, b.shape                      #3 row, 4 columns

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (3, 4))

**Try by yourself**   the following commands *(type or paste the commands in the cell below)*:

    b.ndim                  # Number of dimensions
    b.dtype.name            # Type of data
    b.itemsize              # Size in bytes of elements
    b.size                  # Number of elements in the array

The type of the array can be specified at creation time:

In [138]:
c = np.array([[2.1,3.8], [6.5,7.6]], dtype=np.float64)
print (c)

[[2.1 3.8]
 [6.5 7.6]]


We can modify the type of the array using *.astype()* method (this operation is called **casting**)


However, pay attention when you are *downcasting* it!

In [155]:
ill = c.astype('int64', casting='unsafe') # illegal way 
ill

array([[2, 3],
       [6, 7]])

In [157]:
leg = c.astype('int64', casting='safe') # legal way
leg

TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'

If you want to convert 'legally' a *float* array into an *int*, you can use **round**: 

In [141]:
c_round = np.round(c)
print(c_round, '\n')
print(c_round.astype(int))

[[2. 4.]
 [6. 8.]] 

[[2 4]
 [6 8]]


### 2.1 Array creation functions

Often, the elements of an array are originally unknown, but its size is known. Hence, **NumPy** offers several functions to create arrays with initial placeholder content.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.  
***Try by yourself*** the following commands:

    zeros((3,4))
    ones((3,4))
    empty((2,3))
    eye(3)
    diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

In [165]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
d=np.diag(np.arange(5))   #put the number from 0 to 5 in the main diagonal
d

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

`zeros_like, ones_like` and `empty_like` can be used to create arrays of the same type of a given one

In [167]:
zl=np.zeros_like(c)
zl

array([[0., 0.],
       [0., 0.]])

### 2.2 Sequences and reshaping

Arrays can be created with ***linspace***, ***logspace*** (returning evenly spaced numbers, linear or logarithmic) or ***arange*** and then shaped in matrix form. **mgrid** is like the equivaled "meshgrid" in MATLAB.

In [176]:
np.logspace(1,5,3) # logspace(start, end, num)

array([1.e+01, 1.e+03, 1.e+05])

In [174]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

We can change the shape (and the dimension) of a given array using **reshape** but the new array that we are going to generate must have the same *size* (total number of elements) of the original one.

In [187]:
x_2 = x.reshape(4,3) # equivalent to np.reshape(x,(4,3)) 
print(x_2, '\n\n dim: ', x_2.ndim)

x_3 = x.reshape(-1,2,2)    # '-1' allows to add an unknown dimension (in this case it is 3)
print('\n', x_3, '\n\n dim :', x_3.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

 dim:  2

 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 

 dim : 3


Another way to change the dimension of a given array is **newaxis**:
![](Images/newaxis_image.png)

In [194]:
d = np.linspace(0, 12, 7) # include gli estremi
print (d, 'shape: ', d.shape, '\n')

d_new = d[:, np.newaxis]
print(d_new, '\n\n new shape: ', d_new.shape)

[ 0.  2.  4.  6.  8. 10. 12.] shape:  (7,) 

[[ 0.]
 [ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]
 [12.]] 

 new shape:  (7, 1)


We can use **List comprehension** to create a matrix:


In [196]:
c = np.array([[10*j +i for i in range(3)] for j in range(4)]) # prima fisso j (riga) e poi itero i (colonna)
print (c)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


### 2.3 Random Number Generation

There are several modules of numpy that allow us to generate arrays filled with random numbers from a given probability distribution. All of them are inside the module **.random**

Actually, when we say *random* we do not exactly mean random. Instead, we are talking about algorithms which create **pseudo-random** numbers, which means that if we give to the algorithm a **seed** (a starting point), it will return the same numbers at every run.

These algorithms are massively exploited in every machine learning model, for example when we want to generate new points from a given distribution or when we have to initialize some parameters that we want to learn.
The function *.seed()* could be very useful to study the robustness the model we are building, especially if we are handling small data.

In [221]:
random?

In [218]:
np.random.rand(4,5) # it fills an array of the given shape with uniform random numbers in [0,1]

np.random.seed(42) 

np.random.rand(4,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [219]:
np.random.randn(4,5) # standard normal distributed random numbers

array([[-1.01283112,  0.31424733, -0.90802408, -1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,  0.11092259],
       [-1.15099358,  0.37569802, -0.60063869, -0.29169375, -0.60170661],
       [ 1.85227818, -0.01349722, -1.05771093,  0.82254491, -1.22084365]])

### 2.4 Sparse Matrices

Sparse Matrices are matrices (or more generally *multidimensional arrays*), usually with a huge size, filled mostly with zeros.

Because we are interested in the non-zero elements (which are a tiny percentage) there is a lot of useless information (so wasted memory) inside a sparse matrix.

To solve this problem, there are many formats that allow to compact all the useful information using far less memory. One of these smart formats is **Compressed-Sparse-Row**.

In [208]:
from scipy import sparse

# Create an array with many zeros

#np.random.seed(10)
X = np.random.rand(6,4)

X[X < 0.85] = 0
print (X)

X_csr = sparse.csr_matrix(X) # turn X into a csr (Compressed-Sparse-Row) matrix

print('\n', X_csr)

print('\n Non-zero elements (1D array):', X_csr.data)
print('\n Column indices:', X_csr.indices)
print('\n Points to row starts:', X_csr.indptr) # indptr contains integers such that indptr[i] is the index of the
                                                # element in data which is the first nonzero element of row i.
                                                # If the entire row is zero then indptr[i]==indptr[i+1].
                                                # If the original matrix has m rows then len(indptr)==m+1, because
                                                # the last element is the NNZ (number of non-zero elements).

[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.90864888 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.8568503 ]
 [0.         0.         0.         0.88393648]]

   (2, 0)	0.9086488808086682
  (4, 3)	0.8568503024577332
  (5, 3)	0.8839364795611863

 Non-zero elements (1D array): [0.90864888 0.8568503  0.88393648]

 Column indices: [0 3 3]

 Points to row starts: [0 0 0 1 1 2 3]


In [215]:
print (X_csr.toarray())       # convert back to a dense array

[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.90864888 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.8568503 ]
 [0.         0.         0.         0.88393648]]


There are several other sparse formats that can be useful for various problems:

- `CSC` (compressed sparse column)
- `BSR` (block sparse row)
- `COO` (coordinate)
- `DIA` (diagonal)
- `DOK` (dictionary of keys)

The ``scipy.sparse`` submodule also has a lot of functions for sparse matrices
including linear algebra, sparse solvers, graph algorithms, and much more.

## 3 Basic Array Operations and Linear Algebra

Let's see now how to perform some basic operations on arrays:

In [75]:
M = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
M+2   #add 2 to each element of the array

In [ ]:
M*2   #multiply by 2 each element of the array

In [ ]:
N = np.array([[10,11,0,3],
              [0,9,6,7],
              [8,7,4,1]])
N

In [ ]:
M+N   #classic sum between matrix

In [ ]:
M*N   # This kind of operation is not the classical matrix multiplication! In this case, 
      # we only multiply the elements N(ij) by M(ij). This is called element-wise multiplication (or Hadamard product)

In [ ]:
np.exp(M)   # exponentiation of each elements (it is not the exponentiation of the matrix M)

In [ ]:
# Pay attention to the shape of the matrix you are working with!

L = np.array([[10,11,3],
              [8,7,4]])
M.shape, L.shape

In [ ]:
M+L    #ERROR!

### Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

M+2 is a simple case of broadcasting: it's like you're performing the sum between M and a matrix with same shape of M and with only elements '2'

<![](Images/numpy_broadcasting_image.png)

In [ ]:
P = np.array([range(0,40,10)]*3).T
P

In [ ]:
v=np.array([np.arange(0,3)])
v

In [ ]:
P+v    #broadcasting!

In [ ]:
w=np.array([np.arange(0,3)]).T
w

In [ ]:
w.shape, v.shape

In [ ]:
w+v     #broadcasting!

But.. what about the classic matrix multiplication that we know from algebra? Use the command .dot() and remember that the shape of the two arrays must be aligned! i.e. #columns M = #rows N

In [ ]:
M.dot(N)   #ERROR: #columns M != #rows N

In [ ]:
H = np.array([[0,3],
              [0,7],
              [8,7],
              [11,13]])

In [ ]:
M.shape, H.shape

In [ ]:
M.dot(H)  # MxH classic multiplication between matrices 

**Transpose** of an array: rows become columns and columns become rows

In [ ]:
H.T  #or np.transpose(H)

In [ ]:
H.shape, H.T.shape

**Trace** of a matrix: it is the sum of the matrix diagonal elements. If the matrix is not square, you have to specify what is the diagonal on which compute the trace.

In [ ]:
H.trace()  # trace over first diagonal

In [ ]:
H.trace(1) # trace over the second diagonal

###  Determinant and inverse of a square matrix

The `scipy.linalg.det()` function computes the determinant of a square matrix:

In [ ]:
from scipy import linalg

s = np.array([[1, 2],
               [3, 4]])
s

In [ ]:
linalg.det(s)

The `scipy.linalg.inv()` function computes the inverse of a square matrix:

In [ ]:
print (linalg.inv(s))



### Exercise: Linear Transformation of a vector

Define a function which takes as arguments a matrix *A* and a vector *v* and returns a new vector *w* that is the result of the algebric operation w = A * v.

We also want that this function reshape properly *v* if it is an 1D array in order to transform it into a column vector, which is 2D (i.e. if v.shape is (3,) we want to turn it in (3,1)).

In [123]:
def Linear_Transformation(A, v):
    
    if (A.shape[1] == v.shape[0]):
        
        if (v.ndim == 2 and v.shape[1]==1):
            return(A.dot(v))
        
        elif (v.ndim == 1):
            v = v[:, np.newaxis]
            return(A.dot(v))
        
        else: return('Error: the last array must be a vector!')
    
    else:
        return ('Error')

In [124]:
B = np.array([[0,2,3],
             [8,-5,-1],
             [1,2,3]])
w = np.array([[1,2,3],
             [1,2,3],
             [1,2,3]])
w.ndim

Linear_Transformation(B,w)

'Error: the last array must be a vector!'

### Stacking & concatenation

There are many methods that allow to put together different arrays, with the proper shape. In fact, when we manipulate data, these methods are very useful!

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print (a.shape, b.shape)
print(a)
print('\n', b)

In [ ]:
x = np.concatenate((a, b), axis=0) # join the two matrices a and b: axis=0 --> vertical stack (matrices with same number of columns!)
print (x, x.shape)   

In [ ]:
y = np.concatenate((a, b.T), axis=1) # axis=1 --> horizontal stack (matrices with same number of rows!)
print (y, y.shape)

In [ ]:
print (np.vstack((a,b)))     # vertical concatenation (by rows)
print (np.hstack((a,b.T)))   # horizontal concatenation (by columns)

Other very common methods are *.insert()* and *.append()*

### Other useful commands

In [ ]:
N

In [ ]:
N.min(), N.max()   #to compute the max or the min element of the matrix

In [ ]:
N.mean()  #mean of all elements of the matrix

In [ ]:
N.cumsum(1)   #return the cumulative sum of the elements along a given axis.
              

In [ ]:
N.cumsum()    #the default (None) is to compute the cumsum over the flattened array.

In [ ]:
G = np.array([[1, 2, 2, 2, 4], [1, 4, 2, 1, 2], [1, 2, 4, 4, 2]])
print(np.unique(G))      #return the unique values of the matrix 

## 4 Slicing - Indexing 

Remember: slices (indexed subarrays) are references to memory in the original array, this means that if you modify a slice, you modify the original array. In other words a slice is a pointer to the original array.

### 4.1 Indexing single elements

In [ ]:
M

In [ ]:
#The way to select the element in the position (i,j) is M[i,j]: 
#it returns the element of the matrix M in the row i and in the column j
#For example:

M[2,1]

In [ ]:
M[0,0], M[-1,-1]  #the first and the last element

### 4.2 Indexing by rows and columns

In [ ]:
O = np.array([[0,1,2,3,0,9],
              [4,5,6,7,6,2],
              [8,9,10,11,1,0],
              [0,1,2,3,2,7]])
O

In [ ]:
O[0,2:5]    #from the first row (0), select the elements from position 2 to position 5  

In [ ]:
O[0,2:]    #from the first row (0), select the elements from position 2 to the end

In [ ]:
O[1:4,2:5]   #from the row 2 to the row 4, select the elements from position 2 to position 5
             #this is the way to create a submatrix from a given matrix O!

In [ ]:
O[:, 2]    #all rows, elements of position 2 --> in this way you can select single columns